server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\hanej\Desktop\Study\git-local-repo
        git:
          uri: file:///C:\Users\hanej\Desktop\Study\git-local-repo
